"""updated cart image

Revision ID: 0067739f37ab
Revises: f168abc277d7
Create Date: 2020-01-27 23:50:44.134307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0067739f37ab'
down_revision = 'f168abc277d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('cart_image_file', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'cart_image_file')
    # ### end Alembic commands ###
