"""timestamp

Revision ID: 22d1e5bad53e
Revises: a69194c1ddea
Create Date: 2020-03-21 23:40:50.140143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22d1e5bad53e'
down_revision = 'a69194c1ddea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_order_timestamp'), 'order', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_timestamp'), table_name='order')
    op.drop_column('order', 'timestamp')
    # ### end Alembic commands ###
