"""description image

Revision ID: 692bdcaf875c
Revises: 0db283bcb29e
Create Date: 2020-03-29 20:34:29.665184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692bdcaf875c'
down_revision = '0db283bcb29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('back_image_file', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'back_image_file')
    # ### end Alembic commands ###
