"""remove postcode field

Revision ID: 9b54d7d84839
Revises: 692bdcaf875c
Create Date: 2020-03-31 23:21:21.961794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b54d7d84839'
down_revision = '692bdcaf875c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('postcode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postcode', sa.VARCHAR(length=140), nullable=True))

    # ### end Alembic commands ###
